{% set name = "conda-tree" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rvalieris/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 52c641218e6143607221e212eb11533b315f8f8e2eefe94ebbbf259e1a01b03b

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - conda-tree = conda_tree:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - networkx
    - conda

test:
  commands:
    - conda-tree -h

about:
  home: https://github.com/rvalieris/conda-tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'conda dependency tree helper'
  dev_url: https://github.com/rvalieris/conda-tree
  doc_url: https://github.com/rvalieris/conda-tree

extra:
  recipe-maintainers:
    - xylar
    - rvalieris
