{% set name = "conda-tree" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rvalieris/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 56c0c8764dd27ffc9e7edc6bd38b1e4ce431695f1be9da23463da2a9f7409f71

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-tree = conda_tree:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - networkx
    - conda
    - colorama

test:
  commands:
    - conda-tree -h

about:
  home: https://github.com/rvalieris/conda-tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: conda dependency tree helper
  dev_url: https://github.com/rvalieris/conda-tree
  doc_url: https://github.com/rvalieris/conda-tree

extra:
  recipe-maintainers:
    - xylar
    - rvalieris
