travis:
  secure:
    BINSTAR_TOKEN: XUwpL+qquLRicM7EOLCzEJMrhjshlD+9a8LfJdj2GRYkhp51KWPYT8vCVfwjCMsz/tAGFEMXDAauMiNpz++wFGvcL90UV/oWkB0eezp2MhHAewiZqPM167REZHBluJlEDFW9KvKdv4COWERQ5UXUc08xkGNvgbar5AJBDFAG/v3vy/VS1GuFQVnUIE0E1xLXLJhmsn4bRMCMzgF+pydqncbwVnq/2HUZ1SwWacEsm83SOIx6xlx7tYr9U5oAoc6Q1sZhqMRmolnwvorJGezlqzRrK2DH6r8vnz8CXuqq6Ysn4rBZBIXgMToZmICFHoE0RY6Sii2k9MsU7S9/SjWEPqNzXnJ943+X9sen6cPVAhNylU8usQjl/ETpqmSTn3wP1qvscEzxXzH8V2/P3X9WqgAlzXnU/l7f0yk+60QGEY1mUjlvmCIUpdpWcBAe5cqvA2B2kQNqfpVtSb/3/MgW44VSwrXPZYvHBzPe6RgV2sr9dQVBeY8sxNi+4RbuyE+4qv0mdk/teybXOtvOwnOkHLH2fqFl0Sy2L1+Wl8BAatizieDEgcASQVMxMEl4S2VZURQtw0oKPFSlkNBpaDpL/FlDplx4dg/nWp3xURuTSbBLXFBVaZRdT3tJfpbGFovh4rBKbDS4Z+8pp44ckBDhf/kOPbEEb7Ap6n15elSGWto=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
